export const swaggersDocuments = {
  openapi: "3.0.0",
  info: {
    title: "Task Management API",
    version: "1.0.0",
    description:
      "This is the swagger documentation for the SHREYASH PROJECT API.",
  },
  servers: [
    {
      url: "http://localhost:8000/",
      description: "This is the staging server.",
    },
    {
      url: "http://localhost:8000/",
      description: "This is the live server.",
    },
  ],

  tags: [
    {
      name: "Users",
      description: "The users collection.",
    },
    {
      name: "Comments",
      description: "The comment model description.",
    },
    {
      name: "SubComments",
      description: "The subcomment model description.",
    },
    {
      name: "Logins",
      description: "The login model description.",
    },
    {
      name: "Designations",
      description: "The designation model description",
    },
    {
      name: "Projects",
      description: "The project model description.",
    },
    {
      name: "Tasks",
      description: "The task model descriptions.",
    },

    {},
  ],
  components: {
    schemas: {
      Users: {
        type: "object",
        properties: {
          _id: {
            type: "integer",
            description: "This field is auto generated by mongoDB.",
          },
          userName: {
            type: "string",
            description: "This field store's the user name.",
            example: "xyz xyz",
          },
          email: {
            type: "string",
            description: "This field store's the email of the user.",
            example: "xyz@gmail.com",
          },
          fullName: {
            type: "string",
            description: "This field store's the full name.",
            example: "xyz xyz",
          },
          password: {
            type: "string",
            description: "This field store's the password of the user.",
            example: "Xyz@123456",
          },
          role: {
            type: "string",
            description:
              "This field store's the role of the person whether it is admin or employee",
            example: "admin",
          },
          isDeleted: {
            type: "boolean",
            description:
              "This field status of the employee whether he has resigned or has been removed",
            example: "admin",
          },

          refreshToken: {
            type: "string",
            description: "This field store's the login token of the user.",
          },
          resetPasswordToken: {
            type: "string",
            description:
              "This field stores the reset password token of the user.",
          },
          resetPasswordTokenExpiry: {
            type: "string",
            format: "date",
            description:
              "This field store's the reset password expiry time details.",
          },
          isEmailVerified: {
            type: "boolean",
            description:
              "This field store the status whether the user is verified or not.",
          },
          emailVerificationToken: {
            type: "string",
            description: "This field store the email verification token.",
          },

          created_at: {
            type: "string",
            format: "date",
            description: "This field store the creation time details.",
          },
          updated_at: {
            type: "string",
            format: "date",
            description: "The field store the update time details.",
          },
        },
      },
      Logins: {
        type: "object",
        properties: {
          _id: {
            type: "integer",
            description: "This field is auto generated by mongoDB.",
          },
          user_id: {
            type: "string",
            description: "This field store's the user id for reference.",
            example: "xyz xyz",
          },
          email: {
            type: "string",
            description: "This field store's the email of the user.",
            example: "xyz@gmail.com",
          },
          token: {
            type: "string",
            description: "This field store's the login token of the user.",
          },
          refreshToken: {
            type: "string",
            description:
              "This field stores the reset password token of the user.",
          },
          created_at: {
            type: "string",
            format: "date",
            description: "This field store the creation time details.",
          },
          updated_at: {
            type: "string",
            format: "date",
            description: "The field store the update time details.",
          },
        },
      },
      Designations: {
        type: "object",
        properties: {
          _id: {
            type: "integer",
            description: "This field is auto generated by mongoDB.",
          },
          user: {
            type: "string",
            description: "This field store's the user id for reference.",
            example: "xyz xyz",
          },
          joining_date: {
            type: "string",
            format: "date",
            description: "This field store the joining date of the employee.",
            example: "2020-10-10",
          },
          dob: {
            type: "string",
            format: "date",
            description: "This field store the Date of birth of the employee.",
            example: "2020-10-10",
          },
          contact_number: {
            type: "string",
            description: "This field stores the contact number of the user.",
            example: "123456789",
          },
          contact_address: {
            type: "string",
            format: "date",
            description:
              "This field store the contact address of the employee.",
            example: "2020-10-10",
          },
          designation: {
            type: "string",
            format: "date",
            description: "This field store the designation of the employee.",
            example: "fresher/experienced/junior/senior",
          },
          department: {
            type: "string",
            format: "date",
            description:
              "This field store the department name in which the employee is working",
            example: "it/marketing/sales/bde/account/manager",
          },
          created_at: {
            type: "string",
            format: "date",
            description: "This field store the creation time details.",
          },
          updated_at: {
            type: "string",
            format: "date",
            description: "The field store the update time details.",
          },
        },
      },
      Comments: {
        type: "object",
        properties: {
          _id: {
            type: "integer",
            description: "This field is auto generated by mongoDB.",
          },
          taskId: {
            type: "string",
            description: "This field store's the task id for reference.",
            example: "675fc1a148f59a2cd688d9a6",
          },
          author: {
            type: "string",
            description: "This field store the id for the employee reference.",
            example: "675fc1a148f59a2cd688d9a6",
          },
          content: {
            type: "string",
            description: "This field store the content of the task.",
            example: "content",
          },
          subCommentsIds: [
            {
              type: "string",
              description: "This field stores the subcomments ID.",
              example: "123456789",
            },
          ],
          isDeleted: {
            type: "boolean",
            description: "This field store whether the task is deleted or not",
            example: "2020-10-10",
          },
          created_at: {
            type: "string",
            format: "date",
            description: "This field store the creation time details.",
          },
          updated_at: {
            type: "string",
            format: "date",
            description: "The field store the update time details.",
          },
        },
      },
      Projects: {
        type: "object",
        properties: {
          _id: {
            type: "integer",
            description: "This field is auto generated by mongoDB.",
          },
          name: {
            type: "string",
            description: "This field store the name of the project.",
            example: "xyz project",
          },
          description: {
            type: "string",
            description: "This field store the description of the project.",
            example: "xyz project sds sdsd sdsdsdsd",
          },

          clientName: {
            type: "string",
            description: "This field store the name of the client.",
            example: "Mr XyZ",
          },
          projectNumber: {
            type: "integer",
            description: "This field store the project number.",
            example: "234",
          },
          associatedTask: [
            {
              type: "string",
              description: "This field store the ID of the task.",
            },
          ],

          isDeleted: {
            type: "boolean",
            description: "This field store whether the task is deleted or not",
            example: "2020-10-10",
          },
          created_at: {
            type: "string",
            format: "date",
            description: "This field store the creation time details.",
          },
          updated_at: {
            type: "string",
            format: "date",
            description: "The field store the update time details.",
          },
        },
      },
      subComments: {
        type: "object",
        properties: {
          _id: {
            type: "integer",
            description: "This field is auto generated by mongoDB.",
          },
          commentId: {
            type: "string",
            description: "This field store the comment ID",
            example: "675fc1a148f59a2cd688d9a6",
          },
          userId: {
            type: "string",
            description: "This field store the user ID",
            example: "675fc1a148f59a2cd688d9a6",
          },
          content: {
            type: "String",
            description: "This field store the content of the subcomments.",
          },
          isDeleted: {
            type: "boolean",
            description: "This field store whether the task is deleted or not",
            example: "2020-10-10",
          },
          created_at: {
            type: "string",
            format: "date",
            description: "This field store the creation time details.",
          },
          updated_at: {
            type: "string",
            format: "date",
            description: "The field store the update time details.",
          },
        },
      },
      Tasks: {
        type: "object",
        properties: {
          _id: {
            type: "integer",
            description: "This field is auto generated by mongoDB.",
          },
          title: {
            type: "string",
            description: "This field store the title of the task.",
            example: "This is related to backend.",
          },
          description: {
            type: "string",
            description: "This field store the description of the task.",
            example: "This is related to backend.",
          },
          status: {
            type: "string",
            description: "This field store the status of the task.",
            example: "pending,in-progress,completed,cancelled,missed",
          },
          priority: {
            type: "String",
            description: "This field store the prority of the task.",
            example: "low/medium/high/crictical",
          },
          assignee: {
            type: "String",
            description:
              "This field store the ID of the user to whom the task is assigned.",
            example: "675fc1a148f59a2cd688d9a6",
          },
          assigner: {
            type: "String",
            description:
              "This field store the ID of the user who has assigned the task to other user.",
            example: "675fc1a148f59a2cd688d9a6",
          },
          startDate: {
            type: "string",
            format: "date",
            description: "This field store the start date of the project.",
            example: "2024-05-05",
          },
          dueDate: {
            type: "string",
            format: "date",
            description: "This field store the due date of the project.",
            example: "2024-05-05",
          },

          isDeleted: {
            type: "boolean",
            description: "This field store whether the task is deleted or not",
            example: "2020-10-10",
          },
          created_at: {
            type: "string",
            format: "date",
            description: "This field store the creation time details.",
          },
          updated_at: {
            type: "string",
            format: "date",
            description: "The field store the update time details.",
          },
        },
      },

      Error: {
        type: "object", //data type
        properties: {
          message: {
            type: "string", // data type
            description: "Error message", // desc
            example: "Not found", // example of an error message
          },
          internal_code: {
            type: "string", // data type
            description: "Error internal code", // desc
            example: "Invalid parameters", // example of an error internal code
          },
        },
      },
    },
    securitySchemes: {
      JWT: {
        type: "apiKey",
        name: "Authorization",
        in: "header",
      },
    },
  },
  paths: {
    "/api/v1/auth/login": {
      post: {
        tags: ["Users"],
        consumes: {},
        summary: "Allow the admin to login.",
        description: "Allow the admin to login.",
        // security: [
        //   {
        //     JWT: [],
        //   },
        // ],
        requestBody: {
          required: true,
          content: {
            "application/json": {
              schema: {
                type: "object",
                properties: {
                  email: {
                    type: "string",
                    example: "abc@gmail.com",
                  },
                  password: {
                    type: "string",
                    example: "abc@123",
                  },
                },
              },
            },
          },
        },

        responses: {
          200: {
            description: "OK",
            content: {
              "application/json": {
                schema: {
                  type: "object",
                  items: {
                    type: "string",
                  },
                },
              },
            },
          },
          401: {
            description: "UnAuthorized error",
            content: {
              "application/json": {
                schema: {
                  type: "object",
                  items: {
                    message: "Please enter the valid email and password.",
                  },
                },
              },
            },
          },
          500: {
            description: "forbidden error",
            content: {
              "application/json": {
                schema: {
                  type: "object",
                  items: {
                    message: "Sorry there is some error",
                  },
                },
              },
            },
          },
          default: {
            description: "Unexpected error",
          },
        },
      },
    },
    "/api/v1/auth/logout": {
      get: {
        tags: ["Users"],
        consumes: {},
        summary: "Allow the admin to logout.",
        description: "Allow the admin to logout.",
        security: [
          {
            JWT: [],
          },
        ],
        responses: {
          200: {
            description: "OK",
            content: {
              "application/json": {
                schema: {
                  type: "object",
                  items: {
                    type: "string",
                  },
                },
              },
            },
          },
          401: {
            description: "UnAuthorized error",
            content: {
              "application/json": {
                schema: {
                  type: "object",
                  items: {
                    message: "Please enter the valid email and password.",
                  },
                },
              },
            },
          },
          500: {
            description: "forbidden error",
            content: {
              "application/json": {
                schema: {
                  type: "object",
                  items: {
                    message: "Sorry there is some error",
                  },
                },
              },
            },
          },
          default: {
            description: "Unexpected error",
          },
        },
      },
    },
    "/api/v1/users/forgot-password": {
      post: {
        tags: ["Users"],
        summary: "The reset password link will be send to the given mail.",
        description: "The reset password link will be send to the given mail",
        requestBody: {
          required: true,
          content: {
            "application/json": {
              schema: {
                type: "object",
                properties: {
                  email: {
                    type: "string",
                    example: "abc@gmail.com",
                  },
                },
              },
            },
          },
        },

        responses: {
          200: {
            description: "OK",
            content: {
              "application/json": {
                schema: {
                  type: "object",
                  items: {
                    type: "string",
                  },
                },
              },
            },
          },
          500: {
            description: "Internal server error",
            content: {
              "application/json": {
                schema: {
                  type: "object",
                  items: {
                    message: "Internal server error",
                  },
                },
              },
            },
          },
          default: {
            description: "Unexpected error",
          },
        },
      },
    },
  },
};
